import {
    Application,
    ApplicationStage,
    ApplicationStatus,
    DegreeType,
    Education,
    Experience,
    Gender,
    JobSource,
} from '@jobify/domain/application';
export const jobs: {
    title: string;
    company: string;
    location: string;
    status: string;
    appliedDate: string;
    applicants: {
        name: string;
        email: string;
        phone: string;
        country: string;
        resumeLink: string;
        graduation: string;
        currentJob: string;
        experience: string;
        coverLetter: string;
        skills: string[];
    }[];
}[] = [
    {
        title: 'Software Engineer',
        company: 'Acme Inc.',
        location: 'San Francisco, CA',
        status: 'Pending',
        appliedDate: '2023-04-15',
        applicants: [
            {
                name: 'John Doe',
                email: 'john@example.com',
                phone: '555-1234',
                country: 'USA',
                resumeLink: 'https://example.com/resume-john-doe.pdf',
                graduation: '2018',
                currentJob: 'Frontend Developer',
                experience: '3 years',
                coverLetter: 'I am excited to apply for this role...',
                skills: ['JavaScript', 'React', 'Node.js'],
            },
            {
                name: 'Jane Smith',
                email: 'jane@example.com',
                phone: '555-5678',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-jane-smith.pdf',
                graduation: '2020',
                currentJob: 'Software Engineer',
                experience: '2 years',
                coverLetter: 'I believe my skills and experience make me a great fit...',
                skills: ['Python', 'Django', 'SQL'],
            },
            {
                name: 'Michael Johnson',
                email: 'michael@example.com',
                phone: '555-9012',
                country: 'United Kingdom',
                resumeLink: 'https://example.com/resume-michael-johnson.pdf',
                graduation: '2016',
                currentJob: 'Full-Stack Developer',
                experience: '5 years',
                coverLetter: 'I am passionate about building scalable and efficient applications...',
                skills: ['Java', 'Spring', 'AWS'],
            },
        ],
    },
    {
        title: 'Product Designer',
        company: 'Globex Corp.',
        location: 'New York, NY',
        status: 'Accepted',
        appliedDate: '2023-03-22',
        applicants: [
            {
                name: 'Emily Davis',
                email: 'emily@example.com',
                phone: '555-3456',
                country: 'USA',
                resumeLink: 'https://example.com/resume-emily-davis.pdf',
                graduation: '2019',
                currentJob: 'UI/UX Designer',
                experience: '4 years',
                coverLetter: 'I am excited to bring my design expertise to your team...',
                skills: ['Figma', 'Sketch', 'Adobe Creative Suite'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
            {
                name: 'David Lee',
                email: 'david@example.com',
                phone: '555-7890',
                country: 'Canada',
                resumeLink: 'https://example.com/resume-david-lee.pdf',
                graduation: '2017',
                currentJob: 'Product Designer',
                experience: '3 years',
                coverLetter: 'I am passionate about creating user-centric products...',
                skills: ['Prototyping', 'User Research', 'Interaction Design'],
            },
        ],
    },
    {
        title: 'UI/UX Designer',
        company: 'Stark Industries',
        location: 'Los Angeles, CA',
        status: 'Rejected',
        appliedDate: '2023-02-10',
        applicants: [
            {
                name: 'Samantha Brown',
                email: 'samantha@example.com',
                phone: '555-2345',
                country: 'USA',
                resumeLink: 'https://example.com/resume-samantha-brown.pdf',
                graduation: '2021',
                currentJob: 'Freelance Designer',
                experience: '2 years',
                coverLetter: 'I am excited to apply my design skills to your team...',
                skills: ['Figma', 'Adobe XD', 'User Testing'],
            },
        ],
    },
    {
        title: 'Frontend Developer',
        company: 'Wayne Enterprises',
        location: 'Chicago, IL',
        status: 'Pending',
        appliedDate: '2023-05-01',
        applicants: [
            {
                name: 'Jessica Martinez',
                email: 'jessica@example.com',
                phone: '555-6789',
                country: 'Mexico',
                resumeLink: 'https://example.com/resume-jessica-martinez.pdf',
                graduation: '2019',
                currentJob: 'Frontend Developer',
                experience: '3 years',
                coverLetter: 'I am excited to contribute my frontend development skills...',
                skills: ['HTML', 'CSS', 'JavaScript', 'React'],
            },
            {
                name: 'Robert Hernandez',
                email: 'robert@example.com',
                phone: '555-0123',
                country: 'USA',
                resumeLink: 'https://example.com/resume-robert-hernandez.pdf',
                graduation: '2017',
                currentJob: 'Web Developer',
                experience: '5 years',
                coverLetter: 'I believe my experience makes me a great fit for this role...',
                skills: ['Angular', 'TypeScript', 'Responsive Design'],
            },
        ],
    },
    {
        title: 'Data Analyst',
        company: 'Stark Industries',
        location: 'Seattle, WA',
        status: 'Accepted',
        appliedDate: '2023-03-15',
        applicants: [
            {
                name: 'Olivia Garcia',
                email: 'olivia@example.com',
                phone: '555-4567',
                country: 'USA',
                resumeLink: 'https://example.com/resume-olivia-garcia.pdf',
                graduation: '2018',
                currentJob: 'Data Analyst',
                experience: '4 years',
                coverLetter: 'I am excited to apply my data analysis skills to your team...',
                skills: ['SQL', 'Python', 'Power BI', 'Tableau'],
            },
        ],
    },
];
export const dummyApplications: Application[] = [
    {
        id: '1',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        phone: '+1234567890',
        currentLocation: 'New York, USA',
        gender: Gender.Male,
        education: [
            new Education('MIT', 'Computer Science', DegreeType.BACHELOR, 3.8),
            new Education('Stanford', 'Data Science', DegreeType.MASTER, 3.9),
        ],
        experience: [
            new Experience('Software Engineer', 'Tech Corp', 'Tech Corp', false, '2018-06-01', '2022-05-31', 4),
            new Experience('Senior Developer', 'Innovate Inc', 'Innovate Inc', true, '2022-06-01', '', 2),
        ],
        skills: ['JavaScript', 'React', 'Node.js', 'Python', 'Machine Learning'],
        source: JobSource.LINKEDIN,
        resume: 'resume_link_1.pdf',
        socialLinks: ['https://linkedin.com/in/johndoe', 'https://github.com/johndoe'],
        coverLetter: 'I am excited to apply for this position...',
        status: ApplicationStatus.APPLIED,
        stage: ApplicationStage.APPLIED,
        jobId: 'JOB001',
        createdAt: '2023-08-15T10:00:00Z',
        createdBy: 'SYSTEM',
    },
    {
        id: '2',
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        phone: '+1987654321',
        currentLocation: 'San Francisco, USA',
        gender: Gender.Female,
        education: [
            new Education('Harvard', 'Business Administration', DegreeType.BACHELOR, 3.7),
            new Education('Wharton', 'MBA', DegreeType.MASTER, 3.9),
        ],
        experience: [
            new Experience('Marketing Associate', 'Global Marketing', 'Global Marketing', false, '2019-07-01', '2022-06-30', 3),
            new Experience('Marketing Manager', 'Brand Leaders', 'Brand Leaders', true, '2022-07-01', '', 1),
        ],
        skills: ['Digital Marketing', 'SEO', 'Content Strategy', 'Data Analysis'],
        source: JobSource.REFERRAL,
        resume: 'resume_link_2.pdf',
        socialLinks: ['https://linkedin.com/in/janesmith'],
        coverLetter: 'With my experience in digital marketing...',
        status: ApplicationStatus.SELECTED,
        stage: ApplicationStage.SHORTLISTED,
        jobId: 'JOB002',
        createdAt: '2023-08-16T14:30:00Z',
        createdBy: 'SYSTEM',
    },
    {
        id: '3',
        firstName: 'Alex',
        lastName: 'Johnson',
        email: 'alex.johnson@example.com',
        phone: '+1122334455',
        currentLocation: 'Chicago, USA',
        gender: Gender.Other,
        education: [new Education('University of Chicago', 'Data Science', DegreeType.BACHELOR, 3.6)],
        experience: [new Experience('Data Analyst', 'Data Insights Co', 'Data Insights Co', false, '2020-01-01', '2023-04-30', 3)],
        skills: ['SQL', 'Python', 'Tableau', 'Machine Learning'],
        source: JobSource.JOB_PORTAL,
        resume: 'resume_link_3.pdf',
        socialLinks: ['https://linkedin.com/in/alexjohnson', 'https://github.com/alexj'],
        coverLetter: 'I am passionate about leveraging data to drive business decisions...',
        status: ApplicationStatus.REJECTED,
        stage: ApplicationStage.REJECTED,
        jobId: 'JOB003',
        createdAt: '2023-08-17T09:15:00Z',
        createdBy: 'SYSTEM',
    },
];
export const predefinedSkills = [
    'Software Development',
    'Web Development',
    'Mobile Development',
    'UI/UX Design',
    'Product Management',
    'Marketing',
    'Sales',
    'Customer Support',
    'Data Science',
    'Machine Learning',
    'Artificial Intelligence',
    'Blockchain',
    'Cybersecurity',
    'Cloud Computing',
    'DevOps',
    'Quality Assurance',
    'Game Development',
    'Graphic Design',
    'Video Editing',
    'Content Writing',
    'Copywriting',
    'SEO',
    'Social Media Marketing',
    'Email Marketing',
    'Influencer Marketing',
    'Affiliate Marketing',
    'Public Relations',
    'Event Management',
    'Community Management',
    'Human Resources',
];
export const countries = [
    {
        name: 'Afghanistan',
        dial_code: '+93',
        code: 'AF',
        flag: '🇦🇫',
        local_name: 'افغانستان',
    },
    {
        name: 'Albania',
        dial_code: '+355',
        code: 'AL',
        flag: '🇦🇱',
        local_name: 'Shqipëria',
    },
    {
        name: 'Algeria',
        dial_code: '+213',
        code: 'DZ',
        flag: '🇩🇿',
        local_name: 'Dzayer',
    },
    {
        name: 'American Samoa',
        dial_code: '+1684',
        code: 'AS',
        flag: '🇦🇸',
        part_of: ['US'],
    },
    {
        name: 'Andorra',
        dial_code: '+376',
        code: 'AD',
        flag: '🇦🇩',
        local_name: 'Andorra',
    },
    {
        name: 'Angola',
        dial_code: '+244',
        code: 'AO',
        flag: '🇦🇴',
        local_name: 'Angola',
    },
    {
        name: 'Anguilla',
        dial_code: '+1264',
        code: 'AI',
        flag: '🇦🇮',
        local_name: 'Anguilla',
        part_of: ['GB'],
    },
    { name: 'Antarctica', dial_code: '+672', code: 'AQ', flag: '🇦🇶' },
    { name: 'Antigua and Barbuda', dial_code: '+1268', code: 'AG', flag: '🇦🇬' },
    { name: 'Argentina', dial_code: '+54', code: 'AR', flag: '🇦🇷' },
    { name: 'Armenia', dial_code: '+374', code: 'AM', flag: '🇦🇲' },
    {
        name: 'Aruba',
        dial_code: '+297',
        code: 'AW',
        flag: '🇦🇼',
        part_of: ['NL'],
    },
    {
        name: 'Australia',
        dial_code: '+61',
        code: 'AU',
        preferred: true,
        flag: '🇦🇺',
    },
    { name: 'Austria', dial_code: '+43', code: 'AT', flag: '🇦🇹' },
    { name: 'Azerbaijan', dial_code: '+994', code: 'AZ', flag: '🇦🇿' },
    { name: 'Bahamas', dial_code: '+1242', code: 'BS', flag: '🇧🇸' },
    { name: 'Bahrain', dial_code: '+973', code: 'BH', flag: '🇧🇭' },
    {
        name: 'Bangladesh',
        dial_code: '+880',
        code: 'BD',
        flag: '🇧🇩',
        local_name: 'বাংলাদেশ',
    },
    { name: 'Barbados', dial_code: '+1246', code: 'BB', flag: '🇧🇧' },
    { name: 'Belarus', dial_code: '+375', code: 'BY', flag: '🇧🇾' },
    { name: 'Belgium', dial_code: '+32', code: 'BE', flag: '🇧🇪' },
    { name: 'Belize', dial_code: '+501', code: 'BZ', flag: '🇧🇿' },
    {
        name: 'Benin',
        dial_code: '+229',
        code: 'BJ',
        flag: '🇧🇯',
        local_name: 'Bénin',
    },
    {
        name: 'Bermuda',
        dial_code: '+1441',
        code: 'BM',
        flag: '🇧🇲',
        part_of: ['GB'],
    },
    {
        name: 'Bhutan',
        dial_code: '+975',
        code: 'BT',
        flag: '🇧🇹',
        local_name: 'འབྲུག་ཡུལ',
    },
    {
        name: 'Bolivia, Plurinational State of',
        dial_code: '+591',
        code: 'BO',
        flag: '🇧🇴',
    },
    {
        name: 'Bosnia and Herzegovina',
        dial_code: '+387',
        code: 'BA',
        flag: '🇧🇦',
    },
    { name: 'Botswana', dial_code: '+267', code: 'BW', flag: '🇧🇼' },
    { name: 'Brazil', dial_code: '+55', code: 'BR', flag: '🇧🇷' },
    {
        name: 'British Indian Ocean Territory',
        dial_code: '+246',
        code: 'IO',
        flag: '🇮🇴',
        part_of: ['GB'],
    },
    {
        name: 'Brunei Darussalam',
        dial_code: '+673',
        code: 'BN',
        flag: '🇧🇳',
        local_name: 'بروني',
    },
    { name: 'Bulgaria', dial_code: '+359', code: 'BG', flag: '🇧🇬' },
    { name: 'Burkina Faso', dial_code: '+226', code: 'BF', flag: '🇧🇫' },
    { name: 'Burundi', dial_code: '+257', code: 'BI', flag: '🇧🇮' },
    { name: 'Cambodia', dial_code: '+855', code: 'KH', flag: '🇰🇭' },
    { name: 'Cameroon', dial_code: '+237', code: 'CM', flag: '🇨🇲' },
    { name: 'Canada', dial_code: '+1', code: 'CA', flag: '🇨🇦' },
    { name: 'Cape Verde', dial_code: '+238', code: 'CV', flag: '🇨🇻' },
    {
        name: 'Cayman Islands',
        dial_code: '+345',
        code: 'KY',
        flag: '🇰🇾',
        part_of: ['GB'],
    },
    {
        name: 'Central African Republic',
        dial_code: '+236',
        code: 'CF',
        flag: '🇨🇫',
    },
    { name: 'Chad', dial_code: '+235', code: 'TD', flag: '🇹🇩' },
    { name: 'Chile', dial_code: '+56', code: 'CL', flag: '🇨🇱' },
    {
        name: 'China',
        dial_code: '+86',
        code: 'CN',
        flag: '🇨🇳',
        local_name: '中国',
    },
    {
        name: 'Christmas Island',
        dial_code: '+61',
        code: 'CX',
        flag: '🇨🇽',
        part_of: ['AU'],
    },
    {
        name: 'Cocos (Keeling) Islands',
        dial_code: '+61',
        code: 'CC',
        flag: '🇨🇨',
        part_of: ['AU'],
    },
    { name: 'Colombia', dial_code: '+57', code: 'CO', flag: '🇨🇴' },
    { name: 'Comoros', dial_code: '+269', code: 'KM', flag: '🇰🇲' },
    { name: 'Congo', dial_code: '+242', code: 'CG', flag: '🇨🇬' },
    {
        name: 'Congo, The Democratic Republic of the',
        dial_code: '+243',
        code: 'CD',
        flag: '🇨🇩',
    },
    { name: 'Cook Islands', dial_code: '+682', code: 'CK', flag: '🇨🇰' },
    { name: 'Costa Rica', dial_code: '+506', code: 'CR', flag: '🇨🇷' },
    {
        name: "Cote d'Ivoire",
        dial_code: '+225',
        code: 'CI',
        flag: '🇨🇮',
        local_name: "Côte d'Ivoire",
    },
    {
        name: 'Croatia',
        dial_code: '+385',
        code: 'HR',
        flag: '🇭🇷',
        local_name: 'Hrvatska',
    },
    { name: 'Cuba', dial_code: '+53', code: 'CU', flag: '🇨🇺' },
    { name: 'Cyprus', dial_code: '+357', code: 'CY', flag: '🇨🇾' },
    {
        name: 'Czech Republic',
        dial_code: '+420',
        code: 'CZ',
        flag: '🇨🇿',
        local_name: 'Česko',
    },
    {
        name: 'Curaçao',
        dial_code: '+599',
        code: 'CW',
        flag: '🇨🇼',
        part_of: ['NL'],
    },
    {
        name: 'Canary Islands',
        dial_code: '+34',
        code: 'IC',
        flag: '🇮🇨',
        part_of: ['ES'],
    },
    { name: 'Denmark', dial_code: '+45', code: 'DK', flag: '🇩🇰' },
    {
        name: 'Djibouti',
        dial_code: '+253',
        code: 'DJ',
        flag: '🇩🇯',
        local_name: 'جيبوتي',
    },
    { name: 'Dominica', dial_code: '+1767', code: 'DM', flag: '🇩🇲' },
    {
        name: 'Dominican Republic',
        dial_code: '+1849',
        code: 'DO',
        flag: '🇩🇴',
        country_code: '+1',
        area_codes: ['849', '829', '809'],
    },
    {
        name: 'Dominican Republic',
        dial_code: '+1829',
        code: 'DO',
        flag: '🇩🇴',
        secondary: true,
    },
    {
        name: 'Dominican Republic',
        dial_code: '+1809',
        code: 'DO',
        flag: '🇩🇴',
        secondary: true,
    },
    { name: 'Ecuador', dial_code: '+593', code: 'EC', flag: '🇪🇨' },
    {
        name: 'Egypt',
        dial_code: '+20',
        code: 'EG',
        flag: '🇪🇬',
        local_name: 'مصر',
    },
    { name: 'El Salvador', dial_code: '+503', code: 'SV', flag: '🇸🇻' },
    { name: 'Equatorial Guinea', dial_code: '+240', code: 'GQ', flag: '🇬🇶' },
    { name: 'Eritrea', dial_code: '+291', code: 'ER', flag: '🇪🇷' },
    { name: 'Estonia', dial_code: '+372', code: 'EE', flag: '🇪🇪' },
    {
        name: 'Ethiopia',
        dial_code: '+251',
        code: 'ET',
        flag: '🇪🇹',
        local_name: 'ኢትዮጵያ',
    },
    {
        name: 'Falkland Islands (Malvinas)',
        dial_code: '+500',
        code: 'FK',
        flag: '🇫🇰',
        part_of: ['GB'],
    },
    {
        name: 'Faroe Islands',
        dial_code: '+298',
        code: 'FO',
        flag: '🇫🇴',
        part_of: ['DK'],
    },
    { name: 'Fiji', dial_code: '+679', code: 'FJ', flag: '🇫🇯' },
    { name: 'Finland', dial_code: '+358', code: 'FI', flag: '🇫🇮' },
    { name: 'France', dial_code: '+33', code: 'FR', flag: '🇫🇷' },
    {
        name: 'French Guiana',
        dial_code: '+594',
        code: 'GF',
        flag: '🇬🇫',
        part_of: ['FR'],
    },
    {
        name: 'French Polynesia',
        dial_code: '+689',
        code: 'PF',
        flag: '🇵🇫',
        part_of: ['FR'],
    },
    {
        name: 'French Southern Territories',
        dial_code: '+262',
        code: 'TF',
        flag: '🇹🇫',
        part_of: ['FR'],
    },
    { name: 'Gabon', dial_code: '+241', code: 'GA', flag: '🇬🇦' },
    { name: 'Gambia', dial_code: '+220', code: 'GM', flag: '🇬🇲' },
    {
        name: 'Georgia',
        dial_code: '+995',
        code: 'GE',
        flag: '🇬🇪',
        local_name: 'საქართველო',
    },
    { name: 'Germany', dial_code: '+49', code: 'DE', flag: '🇩🇪' },
    { name: 'Ghana', dial_code: '+233', code: 'GH', flag: '🇬🇭' },
    {
        name: 'Gibraltar',
        dial_code: '+350',
        code: 'GI',
        flag: '🇬🇮',
        part_of: ['GB'],
    },
    {
        name: 'Greece',
        dial_code: '+30',
        code: 'GR',
        flag: '🇬🇷',
        local_name: 'Ελλάς',
    },
    {
        name: 'Greenland',
        dial_code: '+299',
        code: 'GL',
        flag: '🇬🇱',
        part_of: ['DK'],
    },
    { name: 'Grenada', dial_code: '+1473', code: 'GD', flag: '🇬🇩' },
    {
        name: 'Guadeloupe',
        dial_code: '+590',
        code: 'GP',
        flag: '🇬🇵',
        part_of: ['FR'],
    },
    {
        name: 'Guam',
        dial_code: '+1671',
        code: 'GU',
        flag: '🇬🇺',
        part_of: ['US'],
    },
    { name: 'Guatemala', dial_code: '+502', code: 'GT', flag: '🇬🇹' },
    {
        name: 'Guernsey',
        dial_code: '+44',
        code: 'GG',
        flag: '🇬🇬',
        part_of: ['GB'],
    },
    { name: 'Guinea', dial_code: '+224', code: 'GN', flag: '🇬🇳' },
    { name: 'Guinea-Bissau', dial_code: '+245', code: 'GW', flag: '🇬🇼' },
    { name: 'Guyana', dial_code: '+592', code: 'GY', flag: '🇬🇾' },
    { name: 'Haiti', dial_code: '+509', code: 'HT', flag: '🇭🇹' },
    {
        name: 'Heard & McDonald Islands',
        dial_code: '+672',
        code: 'HM',
        flag: '🇭🇲',
        part_of: ['AU'],
    },
    {
        name: 'Holy See (Vatican City State)',
        dial_code: '+379',
        code: 'VA',
        flag: '🇻🇦',
    },
    { name: 'Honduras', dial_code: '+504', code: 'HN', flag: '🇭🇳' },
    {
        name: 'Hong Kong',
        dial_code: '+852',
        code: 'HK',
        flag: '🇭🇰',
        local_name: '香港',
        part_of: ['CN'],
    },
    {
        name: 'Hungary',
        dial_code: '+36',
        code: 'HU',
        flag: '🇭🇺',
        local_name: 'Magyarország',
    },
    {
        name: 'Iceland',
        dial_code: '+354',
        code: 'IS',
        flag: '🇮🇸',
        local_name: 'Ísland',
    },
    {
        name: 'India',
        dial_code: '+91',
        code: 'IN',
        preferred: true,
        flag: '🇮🇳',
        local_name: 'भारत',
    },
    { name: 'Indonesia', dial_code: '+62', code: 'ID', flag: '🇮🇩' },
    {
        name: 'Iran, Islamic Republic of',
        dial_code: '+98',
        code: 'IR',
        flag: '🇮🇷',
        local_name: 'ایران',
    },
    {
        name: 'Iraq',
        dial_code: '+964',
        code: 'IQ',
        flag: '🇮🇶',
        local_name: 'العراق',
    },
    {
        name: 'Ireland',
        dial_code: '+353',
        code: 'IE',
        flag: '🇮🇪',
        local_name: 'Éire',
    },
    {
        name: 'Isle of Man',
        dial_code: '+44',
        code: 'IM',
        flag: '🇮🇲',
        part_of: ['GB'],
    },
    { name: 'Israel', dial_code: '+972', code: 'IL', flag: '🇮🇱' },
    {
        name: 'Italy',
        dial_code: '+39',
        code: 'IT',
        flag: '🇮🇹',
        local_name: 'Italia',
    },
    {
        name: 'Jamaica',
        dial_code: '+1876',
        code: 'JM',
        flag: '🇯🇲',
        country_code: '+1',
        area_codes: ['876', '658'],
    },
    {
        name: 'Jamaica',
        dial_code: '+1658',
        code: 'JM',
        flag: '🇯🇲',
        secondary: true,
    },
    {
        name: 'Japan',
        dial_code: '+81',
        code: 'JP',
        flag: '🇯🇵',
        local_name: '日本',
    },
    {
        name: 'Jersey',
        dial_code: '+44',
        code: 'JE',
        flag: '🇯🇪',
        part_of: ['GB'],
    },
    {
        name: 'Jordan',
        dial_code: '+962',
        code: 'JO',
        flag: '🇯🇴',
        local_name: 'الأردن',
    },
    { name: 'Kazakhstan', dial_code: '+77', code: 'KZ', flag: '🇰🇿' },
    { name: 'Kenya', dial_code: '+254', code: 'KE', flag: '🇰🇪' },
    { name: 'Kiribati', dial_code: '+686', code: 'KI', flag: '🇰🇮' },
    {
        name: "Korea, Democratic People's Republic of",
        dial_code: '+850',
        code: 'KP',
        flag: '🇰🇵',
    },
    { name: 'Korea, Republic of', dial_code: '+82', code: 'KR', flag: '🇰🇷' },
    { name: 'Kuwait', dial_code: '+965', code: 'KW', flag: '🇰🇼' },
    { name: 'Kyrgyzstan', dial_code: '+996', code: 'KG', flag: '🇰🇬' },
    { name: 'Kosovo', dial_code: '+383', code: 'XK', flag: '🇽🇰' },
    {
        name: "Lao People's Democratic Republic",
        dial_code: '+856',
        code: 'LA',
        flag: '🇱🇦',
        local_name: 'ປະເທດລາວ',
    },
    { name: 'Latvia', dial_code: '+371', code: 'LV', flag: '🇱🇻' },
    { name: 'Lebanon', dial_code: '+961', code: 'LB', flag: '🇱🇧' },
    { name: 'Lesotho', dial_code: '+266', code: 'LS', flag: '🇱🇸' },
    { name: 'Liberia', dial_code: '+231', code: 'LR', flag: '🇱🇷' },
    {
        name: 'Libyan Arab Jamahiriya',
        dial_code: '+218',
        code: 'LY',
        flag: '🇱🇾',
    },
    { name: 'Liechtenstein', dial_code: '+423', code: 'LI', flag: '🇱🇮' },
    { name: 'Lithuania', dial_code: '+370', code: 'LT', flag: '🇱🇹' },
    { name: 'Luxembourg', dial_code: '+352', code: 'LU', flag: '🇱🇺' },
    {
        name: 'Macao',
        dial_code: '+853',
        code: 'MO',
        flag: '🇲🇴',
        part_of: ['CN'],
    },
    {
        name: 'Macedonia, The Former Yugoslav Republic of',
        dial_code: '+389',
        code: 'MK',
        flag: '🇲🇰',
    },
    { name: 'Madagascar', dial_code: '+261', code: 'MG', flag: '🇲🇬' },
    { name: 'Malawi', dial_code: '+265', code: 'MW', flag: '🇲🇼' },
    { name: 'Malaysia', dial_code: '+60', code: 'MY', flag: '🇲🇾' },
    { name: 'Maldives', dial_code: '+960', code: 'MV', flag: '🇲🇻' },
    { name: 'Mali', dial_code: '+223', code: 'ML', flag: '🇲🇱' },
    { name: 'Malta', dial_code: '+356', code: 'MT', flag: '🇲🇹' },
    { name: 'Marshall Islands', dial_code: '+692', code: 'MH', flag: '🇲🇭' },
    {
        name: 'Martinique',
        dial_code: '+596',
        code: 'MQ',
        flag: '🇲🇶',
        part_of: ['FR'],
    },
    { name: 'Mauritania', dial_code: '+222', code: 'MR', flag: '🇲🇷' },
    { name: 'Mauritius', dial_code: '+230', code: 'MU', flag: '🇲🇺' },
    {
        name: 'Mayotte',
        dial_code: '+262',
        code: 'YT',
        flag: '🇾🇹',
        part_of: ['FR'],
    },
    { name: 'Mexico', dial_code: '+52', code: 'MX', flag: '🇲🇽' },
    {
        name: 'Micronesia, Federated States of',
        dial_code: '+691',
        code: 'FM',
        flag: '🇫🇲',
    },
    { name: 'Moldova, Republic of', dial_code: '+373', code: 'MD', flag: '🇲🇩' },
    { name: 'Monaco', dial_code: '+377', code: 'MC', flag: '🇲🇨' },
    { name: 'Mongolia', dial_code: '+976', code: 'MN', flag: '🇲🇳' },
    { name: 'Montenegro', dial_code: '+382', code: 'ME', flag: '🇲🇪' },
    { name: 'Montserrat', dial_code: '+1664', code: 'MS', flag: '🇲🇸' },
    { name: 'Morocco', dial_code: '+212', code: 'MA', flag: '🇲🇦' },
    {
        name: 'Mozambique',
        dial_code: '+258',
        code: 'MZ',
        flag: '🇲🇿',
        local_name: 'Moçambique',
    },
    {
        name: 'Myanmar',
        dial_code: '+95',
        code: 'MM',
        flag: '🇲🇲',
        local_name: 'မြန်မာ',
    },
    { name: 'Namibia', dial_code: '+264', code: 'NA', flag: '🇳🇦' },
    { name: 'Nauru', dial_code: '+674', code: 'NR', flag: '🇳🇷' },
    {
        name: 'Nepal',
        dial_code: '+977',
        code: 'NP',
        flag: '🇳🇵',
        local_name: 'नेपाल',
    },
    { name: 'Netherlands', dial_code: '+31', code: 'NL', flag: '🇳🇱' },
    {
        name: 'Caribbean Netherlands',
        dial_code: '+599',
        code: 'BQ',
        flag: '🇧🇶',
        part_of: ['NL'],
    },
    {
        name: 'New Caledonia',
        dial_code: '+687',
        code: 'NC',
        flag: '🇳🇨',
        part_of: ['FR'],
    },
    { name: 'New Zealand', dial_code: '+64', code: 'NZ', flag: '🇳🇿' },
    { name: 'Nicaragua', dial_code: '+505', code: 'NI', flag: '🇳🇮' },
    { name: 'Niger', dial_code: '+227', code: 'NE', flag: '🇳🇪' },
    { name: 'Nigeria', dial_code: '+234', code: 'NG', flag: '🇳🇬' },
    { name: 'Niue', dial_code: '+683', code: 'NU', flag: '🇳🇺' },
    {
        name: 'Norfolk Island',
        dial_code: '+672',
        code: 'NF',
        flag: '🇳🇫',
        part_of: ['AU'],
    },
    {
        name: 'Northern Mariana Islands',
        dial_code: '+1670',
        code: 'MP',
        flag: '🇲🇵',
        part_of: ['US'],
    },
    {
        name: 'Norway',
        dial_code: '+47',
        code: 'NO',
        flag: '🇳🇴',
        local_name: 'Norge',
    },
    {
        name: 'Oman',
        dial_code: '+968',
        code: 'OM',
        flag: '🇴🇲',
        local_name: 'عُمان',
    },
    {
        name: 'Pakistan',
        dial_code: '+92',
        code: 'PK',
        flag: '🇵🇰',
        local_name: 'پاکستان',
    },
    { name: 'Palau', dial_code: '+680', code: 'PW', flag: '🇵🇼' },
    {
        name: 'Palestinian Territory, Occupied',
        dial_code: '+970',
        code: 'PS',
        flag: '🇵🇸',
    },
    { name: 'Panama', dial_code: '+507', code: 'PA', flag: '🇵🇦' },
    { name: 'Papua New Guinea', dial_code: '+675', code: 'PG', flag: '🇵🇬' },
    { name: 'Paraguay', dial_code: '+595', code: 'PY', flag: '🇵🇾' },
    { name: 'Peru', dial_code: '+51', code: 'PE', flag: '🇵🇪' },
    { name: 'Philippines', dial_code: '+63', code: 'PH', flag: '🇵🇭' },
    {
        name: 'Pitcairn',
        dial_code: '+872',
        code: 'PN',
        flag: '🇵🇳',
        part_of: ['GB'],
    },
    { name: 'Poland', dial_code: '+48', code: 'PL', flag: '🇵🇱' },
    { name: 'Portugal', dial_code: '+351', code: 'PT', flag: '🇵🇹' },
    {
        name: 'Puerto Rico',
        dial_code: '+1939',
        code: 'PR',
        flag: '🇵🇷',
        country_code: '+1',
        area_codes: ['939', '787'],
        part_of: ['US'],
    },
    {
        name: 'Puerto Rico',
        dial_code: '+1787',
        code: 'PR',
        flag: '🇵🇷',
        secondary: true,
        part_of: ['US'],
    },
    {
        name: 'Qatar',
        dial_code: '+974',
        code: 'QA',
        flag: '🇶🇦',
        local_name: 'قطر',
    },
    { name: 'Romania', dial_code: '+40', code: 'RO', flag: '🇷🇴' },
    {
        name: 'Russia',
        dial_code: '+7',
        code: 'RU',
        flag: '🇷🇺',
        local_name: 'Россия',
    },
    { name: 'Rwanda', dial_code: '+250', code: 'RW', flag: '🇷🇼' },
    {
        name: 'Réunion',
        dial_code: '+262',
        code: 'RE',
        flag: '🇷🇪',
        part_of: ['FR'],
    },
    {
        name: 'Saint Barthélemy',
        dial_code: '+590',
        code: 'BL',
        flag: '🇧🇱',
        part_of: ['FR'],
    },
    {
        name: 'Saint Helena, Ascension and Tristan Da Cunha',
        dial_code: '+290',
        code: 'SH',
        flag: '🇸🇭',
        part_of: ['GB'],
    },
    {
        name: 'Saint Kitts and Nevis',
        dial_code: '+1869',
        code: 'KN',
        flag: '🇰🇳',
    },
    { name: 'Saint Lucia', dial_code: '+1758', code: 'LC', flag: '🇱🇨' },
    {
        name: 'Saint Martin',
        dial_code: '+590',
        code: 'MF',
        flag: '🇲🇫',
        part_of: ['FR'],
    },
    {
        name: 'Saint Pierre and Miquelon',
        dial_code: '+508',
        code: 'PM',
        flag: '🇵🇲',
        part_of: ['FR'],
    },
    {
        name: 'Saint Vincent and the Grenadines',
        dial_code: '+1784',
        code: 'VC',
        flag: '🇻🇨',
    },
    { name: 'Samoa', dial_code: '+685', code: 'WS', flag: '🇼🇸' },
    { name: 'San Marino', dial_code: '+378', code: 'SM', flag: '🇸🇲' },
    {
        name: 'Sao Tome and Principe',
        dial_code: '+239',
        code: 'ST',
        flag: '🇸🇹',
    },
    { name: 'Saudi Arabia', dial_code: '+966', code: 'SA', flag: '🇸🇦' },
    { name: 'Senegal', dial_code: '+221', code: 'SN', flag: '🇸🇳' },
    { name: 'Serbia', dial_code: '+381', code: 'RS', flag: '🇷🇸' },
    { name: 'Seychelles', dial_code: '+248', code: 'SC', flag: '🇸🇨' },
    { name: 'Sierra Leone', dial_code: '+232', code: 'SL', flag: '🇸🇱' },
    { name: 'Singapore', dial_code: '+65', code: 'SG', flag: '🇸🇬' },
    { name: 'Slovakia', dial_code: '+421', code: 'SK', flag: '🇸🇰' },
    { name: 'Slovenia', dial_code: '+386', code: 'SI', flag: '🇸🇮' },
    { name: 'Solomon Islands', dial_code: '+677', code: 'SB', flag: '🇸🇧' },
    {
        name: 'Somalia',
        dial_code: '+252',
        code: 'SO',
        flag: '🇸🇴',
        local_name: 'الصومال',
    },
    { name: 'South Africa', dial_code: '+27', code: 'ZA', flag: '🇿🇦' },
    {
        name: 'South Georgia and the South Sandwich Islands',
        dial_code: '+500',
        code: 'GS',
        flag: '🇬🇸',
        part_of: ['GB'],
    },
    { name: 'Spain', dial_code: '+34', code: 'ES', flag: '🇪🇸' },
    {
        name: 'Sri Lanka',
        dial_code: '+94',
        code: 'LK',
        flag: '🇱🇰',
        local_name: 'ශ්‍රී ලංකාව',
    },
    {
        name: 'Sudan',
        dial_code: '+249',
        code: 'SD',
        flag: '🇸🇩',
        local_name: 'السودان',
    },
    { name: 'South Sudan', dial_code: '+211', code: 'SS', flag: '🇸🇸' },
    { name: 'Suriname', dial_code: '+597', code: 'SR', flag: '🇸🇷' },
    {
        name: 'Svalbard and Jan Mayen',
        dial_code: '+47',
        code: 'SJ',
        flag: '🇸🇯',
        part_of: ['NO'],
    },
    { name: 'Swaziland', dial_code: '+268', code: 'SZ', flag: '🇸🇿' },
    { name: 'Sweden', dial_code: '+46', code: 'SE', flag: '🇸🇪' },
    { name: 'Switzerland', dial_code: '+41', code: 'CH', flag: '🇨🇭' },
    {
        name: 'Syrian Arab Republic',
        dial_code: '+963',
        code: 'SY',
        flag: '🇸🇾',
        local_name: 'سورية',
    },
    {
        name: 'Sint Maarten',
        dial_code: '+721',
        code: 'SX',
        flag: '🇸🇽',
        part_of: ['NL'],
    },
    {
        name: 'Taiwan, Province of China',
        dial_code: '+886',
        code: 'TW',
        flag: '🇹🇼',
    },
    { name: 'Tajikistan', dial_code: '+992', code: 'TJ', flag: '🇹🇯' },
    {
        name: 'Tanzania, United Republic of',
        dial_code: '+255',
        code: 'TZ',
        flag: '🇹🇿',
    },
    {
        name: 'Thailand',
        dial_code: '+66',
        code: 'TH',
        flag: '🇹🇭',
        local_name: 'เมืองไทย',
    },
    { name: 'Timor-Leste', dial_code: '+670', code: 'TL', flag: '🇹🇱' },
    { name: 'Togo', dial_code: '+228', code: 'TG', flag: '🇹🇬' },
    { name: 'Tokelau', dial_code: '+690', code: 'TK', flag: '🇹🇰' },
    { name: 'Tonga', dial_code: '+676', code: 'TO', flag: '🇹🇴' },
    { name: 'Trinidad and Tobago', dial_code: '+1868', code: 'TT', flag: '🇹🇹' },
    {
        name: 'Tunisia',
        dial_code: '+216',
        code: 'TN',
        flag: '🇹🇳',
        local_name: 'تونس',
    },
    { name: 'Turkey', dial_code: '+90', code: 'TR', flag: '🇹🇷' },
    { name: 'Turkmenistan', dial_code: '+993', code: 'TM', flag: '🇹🇲' },
    {
        name: 'Turks and Caicos Islands',
        dial_code: '+1649',
        code: 'TC',
        flag: '🇹🇨',
        part_of: ['GB'],
    },
    { name: 'Tuvalu', dial_code: '+688', code: 'TV', flag: '🇹🇻' },
    { name: 'Uganda', dial_code: '+256', code: 'UG', flag: '🇺🇬' },
    { name: 'Ukraine', dial_code: '+380', code: 'UA', flag: '🇺🇦' },
    {
        name: 'United Arab Emirates',
        dial_code: '+971',
        code: 'AE',
        preferred: true,
        flag: '🇦🇪',
    },
    {
        name: 'United Kingdom',
        dial_code: '+44',
        code: 'GB',
        preferred: true,
        flag: '🇬🇧',
    },
    {
        name: 'United States',
        dial_code: '+1',
        code: 'US',
        preferred: true,
        flag: '🇺🇸',
    },
    { name: 'Uruguay', dial_code: '+598', code: 'UY', flag: '🇺🇾' },
    { name: 'Uzbekistan', dial_code: '+998', code: 'UZ', flag: '🇺🇿' },
    { name: 'Vanuatu', dial_code: '+678', code: 'VU', flag: '🇻🇺' },
    {
        name: 'Venezuela, Bolivarian Republic of',
        dial_code: '+58',
        code: 'VE',
        flag: '🇻🇪',
    },
    {
        name: 'Vietnam',
        dial_code: '+84',
        code: 'VN',
        flag: '🇻🇳',
        local_name: 'Việt Nam',
    },
    {
        name: 'Virgin Islands, British',
        dial_code: '+1284',
        code: 'VG',
        flag: '🇻🇬',
        part_of: ['GB'],
    },
    {
        name: 'Virgin Islands, U.S.',
        dial_code: '+1340',
        code: 'VI',
        flag: '🇻🇮',
        part_of: ['US'],
    },
    { name: 'Wallis and Futuna', dial_code: '+681', code: 'WF', flag: '🇼🇫' },
    { name: 'Western Sahara', dial_code: '+212', code: 'EH', flag: '🇪🇭' },
    {
        name: 'Yemen',
        dial_code: '+967',
        code: 'YE',
        flag: '🇾🇪',
        local_name: 'اليمن',
    },
    { name: 'Zambia', dial_code: '+260', code: 'ZM', flag: '🇿🇲' },
    { name: 'Zimbabwe', dial_code: '+263', code: 'ZW', flag: '🇿🇼' },
    {
        name: 'Åland Islands',
        dial_code: '+358',
        code: 'AX',
        flag: '🇦🇽',
        part_of: ['FI'],
    },
];
export const APPLICANTS_DEFAULT_PAGE_SIZE = 5;
export const REJECTION_EMAIL_CONTENT = `Dear {firstName} {lastName},

Thank you for applying for {jobTitle} role at {company}. After careful review, we won’t be moving forward with you. We appreciate your time & encourage you to apply for future. Best wishes in your job search.

Sincerely,
{company} Recruitment Team
`;
export const INTERVIEW_EMAIL_CONTENT = `Dear {firstName} {lastName},

Congratulations! You've been selected to advance in recruitment process for {jobTitle} position at {company}. We'll contact you soon to schedule next steps. Thank you for your interest, and we look forward to speak with you.

Best, {company} Recruitment Team
    `;
export const SELECTION_EMAIL_CONTENT = `Dear {firstName} {lastName},

Congrats! You’ve been selected to move forward for the {jobTitle} role at {company}. Your experience impressed us. We’ll contact you soon. Look out for an email with details. Thanks for your interest!

Best,
{company} Recruitment Team
    `;
export const EMAIL_SUBJECT = 'Application Status Update';
